#include <stdio.h>
#include <stdlib.h>
#include "gba.h"
#include "game.h"
#include "mainGame.h"
#include "images/title.h"
#include "images/subtitle1.h"
#include "images/subtitle2.h"
#include "images/badend1.h"
#include "images/badend2.h"
#include "images/win.h"
                    /* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"


                    /* TODO: */
// Add any additional states you need for your app.
typedef enum {
    START,
    START1,
    START2,
    PLAY,
    WIN,
    LOSE1,
    LOSE2,
} GBAState;



int main(void) {
                    /* TODO: */
    // Manipulate REG_DISPCNT here to set Mode 3. //
    REG_DISPCNT = MODE3 | BG2_ENABLE;


    // Save current and previous state of button input.
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

    // Load initial game state
    GBAState state = START;

    int initialized = 0;
    while (1) {
        currentButtons = BUTTONS; // Load the current state of the buttons


                    /* TODO: */
        // Manipulate the state machine below as needed //
        // NOTE: Call waitForVBlank() before you draw
        if(KEY_DOWN(BUTTON_SELECT, currentButtons)) {
            state = START;
            initialized = 0;
        }
        waitForVBlank();

        switch(state) {
            case START:
                drawFullScreenImageDMA(title);
                if(KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
                    state = START1;
                }
                break;
            case START1:
                drawFullScreenImageDMA(subtitle1);
                if(KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
                    state = START2;
                }
                break;

            case START2:
                drawFullScreenImageDMA(subtitle2);
                if(KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
                    state = PLAY;
                }
                break;
            case PLAY:
                if(initialized == 0) {
                    initializeGame();
                    initialized = 1;
                }
                int update = updateGame(currentButtons, previousButtons);
                if(update == 0) {
                    continue;
                }
                else if(update == 1) {
                    state = LOSE1;
                }
                else if(update == 2) {
                    state = WIN;
                }
                break;
            case WIN:
                initialized = 0;
                drawFullScreenImageDMA(win);
                break;
            case LOSE1:
                drawFullScreenImageDMA(badend1);
                if(KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
                    state = LOSE2;
                }
                break;
            case LOSE2:
                initialized = 0;
                drawFullScreenImageDMA(badend2);
                break;
        }



        previousButtons = currentButtons; // Store the current state of the buttons
    }

    UNUSED(previousButtons); // You can remove this once previousButtons is used

    return 0;
}
